### ISSUE TITLE
auth_uid missing

### ISSUE THREAD

**Issue by fyhtma** [M-rcus/OnlyFans-Cookie-Helper#12]
in line "cookie" part

`auth_uid_(NUMBERS)=;",
`
 doesnt print auth_uid, so exported text doesn't work in of-scraper. Tried to log in to OF several times and re-export cookies. Using WIN10 and Firefox 127.0.1 (64-bit)

**Comment by M-rcus** [comment]
Your issue is most likely caused by the OF auth changes and not any missing values from the extension (I say that because I just copied the values as-is earlier without any issues).

Check datawhores/OF-Scraper#402 for fixes you can apply to your version of the software to make it work again.  
If you run a recent enough version, you should be able to just update your config.json for of-scraper.
