### ISSUE TITLE
".profiles/default/auth.json" (OnlyFans Downloader made updates)

### ISSUE THREAD

**Issue by ElusiveZatchmo** [M-rcus/OnlyFans-Cookie-Helper#5]
The OnlyFans downloader as changed how the settings are organized and what is grabbed. Is it possible to get an update to account for the latest version of the downloader?

**Comment by M-rcus** [comment]
I suppose I should, but the extension isn't "missing" any information necessary so I've been kinda lazy about.
The downloader software will fill in anything extra "filler values" (since they're not being used).

Here's a default `auth.json` created on a first-time start of the software itself:
```json
{
  "auth": {
    "username": "",
    "auth_id": "",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "",
    "email": "",
    "password": "",
    "support_2fa": true,
    "active": true
  }
}
```

Here's an example JSON that the cookie helper extension gives (with censored information):
```json
{
  "auth_hash": "",
  "auth_id": "<REDACTED>",
  "auth_uniq_": "",
  "sess": "<REDACTED>",
  "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
  "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0",
  "support_2fa": true,
  "username": "<REDACTED>",
  "active": true
}
```

All you really have to do, is replace the object that comes after `"auth": ` with the one from the cookie helper. Should look like this:
```json
{
  "auth": {
    "auth_hash": "",
    "auth_id": "<REDACTED>",
    "auth_uniq_": "",
    "sess": "<REDACTED>",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla/5.0 (X11; Linux x86_64; rv:88.0) Gecko/20100101 Firefox/88.0",
    "support_2fa": true,
    "username": "<REDACTED>",
    "active": true
  }
}
```

Once you run the downloader software, it will update the `auth.json` to contain the missing filler values:
```json
{
  "auth": {
    "username": "<REDACTED>",
    "auth_id": "<REDACTED>",
    "auth_hash": "",
    "auth_uniq_": "",
    "sess": "<REDACTED>",
    "app_token": "33d57ade8c02dbc5a333db99ff9ae26a",
    "user_agent": "Mozilla\/5.0 (X11; Linux x86_64; rv:88.0) Gecko\/20100101 Firefox\/88.0",
    "email": "",
    "password": "",
    "support_2fa": true,
    "active": true
  }
}
```

I'll leave this issue open though, since ideally the cookie helper extension should wrap it inside the `"auth"` object by default.

**Comment by M-rcus** [comment]
Version 1.0.3 has been released that addresses this: https://github.com/M-rcus/OnlyFans-Cookie-Helper/releases/tag/1.0.3
