### ISSUE TITLE
x-bc header

### ISSUE THREAD

**Issue by estif2127** [M-rcus/OnlyFans-Cookie-Helper#7]
there is x-bc requirement now, could you please add it, thank you

**Comment by M-rcus** [comment]
This is going to take some time to sort out, since the `x_bc` value isn't part of the same "cookies" as all the other values, meaning it adds some complication to it.

As a temporary workaround, you can open the developer tools on OnlyFans and put this into the console: `copy(localStorage.bcTokenSha)`

That console command should put a 40 character long text into your clipboard, which you can put as the `x_bc` value in auth.json (may need to run the OnlyFans scraper software first, so that it can add the `x_bc` field).
